#ifndef __OBDIIHANDLER_H
#define __OBDIIHANDLER_H

/* Dependencies */

#include "typedefs.h"

/* Configurations */

#define MAX_DATAFIELD_SIZE 50
#define OBDII_CAN_ID_REQUEST 0x7DF
#define OBDII_RESPONSE_EXPECTED 0x7E8
#define OBDII_FLOWCONTROL_CANID 0x7E0



/* Data Structures */
#define OBDIIHandler_TEST_ON UT

typedef enum 
{
    ISO_CAN_15765,
    ISO_UART_14230,
    ISO_VPW,
    ISO_PWM
}OBDII_Protocols;

typedef enum
{
    PID_PIDS_SUPPORTED_1_20 = 0,
    PID_DTC_STATUS,
    PID_FREEZE_DTC,
    PID_FUEL_SYSTEM_STATUS,
    PID_ENGINE_LOAD_VALUE,
    PID_ENGINE_COOLANT_TEMPERATURE,
    PID_SHORT_FUEL_TERM_BANK1,
    PID_SHORT_FUEL_TERM_BANK2,
    PID_LONG_FUEL_TERM_BANK1,
    PID_LONG_FUEL_TERM_BANK2,
    PID_FUEL_PRESSURE,
    PID_INTAKE_MANIFOLD_ABSOLUTE_PRESSURE,
    PID_ENGINE_RPM,
    PID_VEHICLE_SPEED,
    PID_TIMING_ADVANCE,
    PID_INTAKE_AIR_TEMPERATURE,
    PID_AIR_FLOW_RATE,
    PID_THROTTLE_POSITION,
    PID_COMMANDED_SECONDARY_AIR_STATUS,
    PID_OXYGEN_SENSOR_PRESENT_IN_2_BANKS,
    PID_OXYGEN_SENSOR_1_VOLTAGE_FUEL,
    PID_OXYGEN_SENSOR_2_VOLTAGE_FUEL,
    PID_OXYGEN_SENSOR_3_VOLTAGE_FUEL,
    PID_OXYGEN_SENSOR_4_VOLTAGE_FUEL,
    PID_OXYGEN_SENSOR_5_VOLTAGE_FUEL,
    PID_OXYGEN_SENSOR_6_VOLTAGE_FUEL,
    PID_OXYGEN_SENSOR_7_VOLTAGE_FUEL,
    PID_OXYGEN_SENSOR_8_VOLTAGE_FUEL,
    PID_OBD_STANDARDS_THIS_VEHICLE_CONFORMS_TO,
    PID_OXYGEN_SENSOR_PRESENT_IN_4_BANKS,
    PID_AUXILIARY_INPUT_STATUS,
    PID_RUN_TIME_SINCE_ENGINE_STARTS,
    PID_PIDS_SUPPORTED_21_40,
    PID_DISTANCE_TRAVELED_WITH_MIL_ON,
    PID_FUEL_RAIL_PRESSURE,
    PID_FUEL_RAIL_GAUGE_PRESSURE,
    PID_OXYGEN_SENSOR_1_RATIO_VOLTAGE,
    PID_OXYGEN_SENSOR_2_RATIO_VOLTAGE,
    PID_OXYGEN_SENSOR_3_RATIO_VOLTAGE,
    PID_OXYGEN_SENSOR_4_RATIO_VOLTAGE,
    PID_OXYGEN_SENSOR_5_RATIO_VOLTAGE,
    PID_OXYGEN_SENSOR_6_RATIO_VOLTAGE,
    PID_OXYGEN_SENSOR_7_RATIO_VOLTAGE,
    PID_OXYGEN_SENSOR_8_RATIO_VOLTAGE,
    PID_COMMANDED_EGR,
    PID_EGR_ERROR,
    PID_COMMANDED_EVAPORATIVE_PURGE,
    PID_FUEL_TANK_LEVEL_INPUT,
    PID_WARM_UPS_SINCE_CODES_CLEARED,
    PID_DISTANCE_TRAVELED_SINCE_CODES_CLEARED,
    PID_EVAP_SYSTEM_VAPOR_PRESSURE,
    PID_ABSOLUTE_BAROMETRIC_PRESSURE,
    PID_OXYGEN_SENSOR_1_RATIO_CURRENT,
    PID_OXYGEN_SENSOR_2_RATIO_CURRENT,
    PID_OXYGEN_SENSOR_3_RATIO_CURRENT,
    PID_OXYGEN_SENSOR_4_RATIO_CURRENT,
    PID_OXYGEN_SENSOR_5_RATIO_CURRENT,
    PID_OXYGEN_SENSOR_6_RATIO_CURRENT,
    PID_OXYGEN_SENSOR_7_RATIO_CURRENT,
    PID_OXYGEN_SENSOR_8_RATIO_CURRENT,
    PID_CATALYST_TEMPERATURE_BANK1_SENSOR1,
    PID_CATALYST_TEMPERATURE_BANK2_SENSOR1,
    PID_CATALYST_TEMPERATURE_BANK1_SENSOR2,
    PID_CATALYST_TEMPERATURE_BANK2_SENSOR2,
    PID_PIDS_SUPPORTED_41_60,
    PID_MONITOR_STATUS_THIS_DRIVE_CYCLE,
    PID_CONTROL_MODULE_VOLTAGE,
    PID_ABSOLUTE_LOAD_VALUE,
    PID_COMMANDED_AIR_FUEL_EQ_RATIO,
    PID_RELATIVE_THROTTLE_POSITION,
    PID_AMBIENT_AIR_TEMPERATURE,
    PID_ABSOLUTE_THROTTLE_POSITION_B,
    PID_ABSOLUTE_THROTTLE_POSITION_C,
    PID_ABSOLUTE_THROTTLE_POSITION_D,
    PID_ABSOLUTE_THROTTLE_POSITION_E,
    PID_ABSOLUTE_THROTTLE_POSITION_F,
    PID_COMMANDED_THROTTLE_ACTUATOR,
    PID_TIME_RUN_WITH_MIL_ON,
    PID_TIME_SINCE_TROUBLE_CODES_CLEARED,
    PID_MAX_VALUES_FOR_SENSORS,
    PID_MAX_VALUES_FOR_AIRFLOWRATE,
    PID_FUEL_TYPE,
    PID_ETHANOL_FUEL,
    PID_ABSOLUTE_EVAP_SYSTEM_VAPOR_PRESSURE,
    PID_EVAP_SYSTEM_VAPORT_PRESSURE,
    PID_SHORT_TERM_SECONDARY_OXYGEN_SENSOR_TRIM_BANK1_BANK3,
    PID_LONG_TERM_SECONDARY_OXYGEN_SENSOR_TRIM_BANK1_BANK3,
    PID_SHORT_TERM_SECONDARY_OXYGEN_SENSOR_TRIM_BANK2_BANK4,
    PID_LONG_TERM_SECONDARY_OXYGEN_SENSOR_TRIM_BANK2_BANK4,
    PID_FUEL_RAIL_ABSOLUTE_PRESSURE,
    PID_RELATIVE_ACCELERATOR_PREDAL_POSITION,
    PID_HYBRID_BATTERY_PACK_REMAINING_LIFE,
    PID_ENGINE_OIL_TEMPERATURE,
    PID_FUEL_INJECTION_TIMING,
    PID_ENGINE_FUEL_RATE,
    PID_EMISSIONS_REQUIREMENTS,
    PID_PIDS_SUPPORTED_61_80,
    PID_DRIVER_DEMAND_ENGINE_TORQUE,
    PID_ACTUAL_ENGINE_TORQUE,
    PID_ENGINE_REFERENCE_TORQUE,
    PID_ENGINE_PERCENT_TORQUE_DATA,
    PID_AUXILIARY_INPUT_OUTPUT_STATUS,
    PID_MASS_AIR_FLOW_SENSOR,
    PID_ENGINE_COOLANT_TEMPERATURE_SENSOR_1,
    PID_INTAKE_AIR_TEMPERATURE_SENSOR_1,

    PID_COMMANDED_EGR_AND_EGR_ERROR,
    PID_COMMANDED_DEISEL_INTAKE_AIR,
    PID_EXHAUST_GAS_RECIRCULATION_TEMPERATURE,
    PID_COMMANDED_THROTTLE_ACTUATOR_CONTROL,
    PID_FUEL_PRESSURE_CONTROL_SYSTEM,
    PID_INJECTION_PRESSURE_CONTROL_SYSTEM,
    PID_TURBO_CHARGER_COMPRESSOR_INLET_PRESSURE,
    PID_BOOST_PRESSURE_CONTROL,
    PID_VGT_CONTROL,
    PID_WASTE_GATE_CONTROL,
    PID_EXHAUST_PRESSURE,
    PID_TURBO_CHARGER_RPM,
    PID_TURBO_CHARGER_TEMP_1,
    PID_TURBO_CHARGER_TEMP_2,
    PID_CHARGE_AIR_COOLER_TEMP,
    PID_EXHAUST_GAS_TEMP_BANK1,
    PID_EXHAUST_GAS_TEMP_BANK2,
    PID_DIESEL_PARTICULATE_FILTER_PRESSURE,
    PID_DIESEL_PARTICULATE_FILTER,
    PID_DIESEL_PARTICULATE_FILTER_TEMP,
    PID_NOX_NTE,
    PID_PM_NTE,
    PID_ENGINE_RUN_TIME,
    PID_PIDS_SUPPORTED_81_A0,
    PID_ENGINE_RUN_TIME_FOR_AUX_EMISSIONS_CONTROL_1,
    PID_ENGINE_RUN_TIME_FOR_AUX_EMISSIONS_CONTROL_2,
    PID_NOX_SENSOR,
    PID_MANIFOLD_SURFACE_TEMPERATURE,
    PID_NOX_REGEANT_SYSTEM,
    PID_PM_SENSOR,
    PID_INTAKE_MANIFOLD_ABSOLUTE_PRESSURE_2,
    PID_SCR_INDUCE_SYSTEM,
    PID_RUN_TIME_FOR_AECD_11_15,
    PID_RUN_TIME_FOR_AECD_16_20,
    PID_DIESEL_AFTERTREATMENT,
    PID_O2_SENSOR,
    PID_THROTTLE_POSITION_G,
    PID_ENGINE_FRICTION_PERCENT_TORQUE,
    PID_PM_SENSOR_BANK_1_AND_2,
    PID_VEHICLE_OBD_SYSTEM_INFO_1,
    PID_VEHICLE_OBD_SYSTEM_INFO_2,
    PID_FUEL_SYSTEM_CONTROL,
    PID_OBD_COUNTERS_SUPPORT,
    PID_NOX_WARNING_AND_INDUCMENT_SYSTEM,
    PID_RES1,
    PID_RES2,
    PID_RES3,
    PID_EXHAUST_GAS_TEMPERATURE,
    PID_EXHAUST_GAS_TEMPERATURE_2,
    PID_HYBRID_EV_SYSTEM_DATA,
    PID_DATA_EXHAUST_FLUID_SENSOR_DATA,
    PID_O2_SENSOR_DATA,
    PID_ENGINE_FUEL_RATE_2,
    PID_ENGINE_EXHAUST_FLOW_RATE,
    PID_FUEL_SYSTEM_PERCENTAGE,
    PID_PIDS_SUPPORTED_A1_C0,
    PID_NOX_SENSOR_CORRECTED_DATA,
    PID_CYLINDER_FUEL_RATE,
    PID_EVAP_SYSTEM_VAPOR_PRESSURE_2,
    PID_TRANSMISSION_ACTUAL_GEAR,
    PID_COMMANDED_DIESEL_EXHAUST_FLUID_DOSING,
    PID_ODOMETER,
    PID_NOX_SENSOR_CONCENTRATION_SENSOR_3_4,
    PID_NOX_SENSOR_CORRECTED_CONCENTRATION_SENSOR_3_4,
    PID_ABS_DISABLE_SWITCH_STATE,
    PID_RES4,
    PID_RES5,
    PID_RES6,
    PID_RES7,
    PID_RES8,
    PID_RES9,
    PID_RES10,
    PID_RES11,
    PID_RES12,
    PID_RES13,
    PID_RES14,
    PID_RES15,
    PID_RES16,
    PID_RES17,
    PID_RES18,
    PID_RES19,
    PID_RES20,
    PID_RES21,
    PID_RES22,
    PID_RES23,
    PID_RES24,
    PID_RES25,
    PID_PIDS_SUPPORTED_C1_E0,
    PID_RES31,
    PID_RES32,
    PID_FUEL_LEVEL_INPUT_AB,
    PID_EXHUAST_PARTICULATE_CONTROL_SYSTEM_DIAGNOSTICS,
    PID_FUEL_PRESSURE_A_AND_B,
    PID_DRIVER_DATA,
    PID_DISTANCE_SINCE_REFLASH_OR_MODULE_REPLACMENT,
    PID_NOX_CONTROL_DIAGNOSTICS,

    OBD_MESSAGES_SIZE
}OBDII_MsgID_e;

typedef enum 
{
    VI_SUPPORTED_PIDS = 0,
    VI_VIN_MESSAGE_COUNT,
    VI_VIN,
    VI_CALIBRATION_ID_COUNT,
    CALIBRATION_ID,
    CALIBRATION_VERIFICATION_NUMBER_COUNT,
    CALIBRATION_VERIFICATION_NUMBER,
    INUSE_PERFORMANCE_TRACK_COUNT,
    INUSE_PERFORMANCE_TRACK_FOR_SPARK_IGNITION_VEHICLES,
    ECU_NAME_COUNT,
    ECU_NAME,
    INUSE_PERFORMANCE_TRACK_FOR_COMPRESSION_IGNITION_VEHICLES,

}OBDII_VehicleInfoID_e;

typedef struct
{
    u8_t bytes;
    u8_t mode;
    u8_t pid;
    u8_t A;
    u8_t B;
    u8_t C;
    u8_t D;
}OBDIIRequestFrame_t;


typedef enum
{
    OBDII_IDLE = 0,
    OBDII_TRANSMIT_SENT,
    OBDII_RESPONSE_WAITING,
    OBDII_RESPONSE_CPLT,
    OBDII_TRANSMIT_FAILED,
    OBDII_RESPONSE_FAILED
}OBDIIRequestStatus_e;

typedef enum
{
    SHOW_DTCS = 3,
    CLEAR_DTCS = 4,
    TEST_RESULTS = 6,
    PENDING_DTCS = 7,
    PERMANENT_DTCS = 0x0A, 
}OBDII_DTCsRequest_e;

typedef struct 
{
    u8_t Buffer[MAX_DATAFIELD_SIZE];
    u8_t Mode;
    u8_t Pid;
    u32_t Length;
}OBDResponse_s;

/* APIs */
/**
 * @brief initialize the OBDII application
 * 
 */
void OBDII_Initialize(void);

/**
 * @brief runs all OBD protocols untill vehicle responds to one of them
 * 
 * @return true succeeded
 * @return false failed
 */
bool OBDII_DetectVehicleProtocol(void);

/**
 * @brief OBD Mode 1: show current data
 * 
 * @param pid 
 * @return true transmit succeeded
 * @return false transmit failed
 */
bool OBDIIRequestMode1(OBDII_MsgID_e  pid);

/**
 * @brief OBD Mode 2: show freeze frame data
 * 
 * @param msg_id 
 * @param frame_number 
 * @return true transmit succeeded
 * @return false transmit failed
 */
bool OBDIIRequestMode2(OBDII_MsgID_e  pid, u8_t frame_number);

/**
 * @brief OBD Mode 9: request vehicle information
 * 
 * @param msg_id 
 * @return true transmit succeeded
 * @return false transmit failed
 */
bool OBDIIRequestMode9(OBDII_VehicleInfoID_e  pid);

/**
 * @brief OBD Mode DTCs: could be one of @ref OBDII_DTCsRequest_e
 * 
 * @param msg_id 
 * @return true 
 * @return false 
 */
bool OBDIIRequestModeDTCs(OBDII_DTCsRequest_e msg_id);

/**
 * @brief copies the OBD response to the user
 * 
 * @param outputResponse user object
 * @return true receive successed
 * @return false receive failed
 */
bool OBDIIReceiveResponse(OBDResponse_s* outputResponse);


void OBDII_SetTxCallback(pFunction tx_callback);

void OBDII_SetRxCallback(pFunction Rx_callback);

#endif
